"""Text-to-timestamp alignment using word-level Whisper data.

This module provides functionality to align text excerpts from an LLM
with actual word-level timestamps from Whisper transcription.
"""

import logging
import re
from dataclasses import dataclass
from typing import Optional

from auto_video.core.subtitles import WordTimestamp

logger = logging.getLogger(__name__)


@dataclass
class TextMatch:
    """Result of matching text to timestamps.

    Attributes:
        start_time: Start time in seconds.
        end_time: End time in seconds.
        confidence: How well the text matched (0.0-1.0).
    """

    start_time: float
    end_time: float
    confidence: float


class TextToTimestampAligner:
    """Matches text excerpts to word-level timestamps.

    This aligner uses word-level timestamps from Whisper to find the
    precise timing for text excerpts generated by an LLM. It uses
    sequential search to ensure consistent progression through the audio.

    Example:
        words = [
            WordTimestamp(word="Hello", start=0.0, end=0.3),
            WordTimestamp(word="world", start=0.4, end=0.8),
            WordTimestamp(word="how", start=0.9, end=1.1),
            WordTimestamp(word="are", start=1.2, end=1.4),
            WordTimestamp(word="you", start=1.5, end=1.8),
        ]
        aligner = TextToTimestampAligner(words)

        # First segment: "Hello world"
        match1 = aligner.find_timing_for_text("Hello world")
        # match1.start_time = 0.0, match1.end_time = 0.8

        # Second segment: "how are you"
        match2 = aligner.find_timing_for_text("how are you")
        # match2.start_time = 0.9, match2.end_time = 1.8
    """

    def __init__(self, word_timestamps: list[WordTimestamp]) -> None:
        """Initialize the aligner with word-level timestamps.

        Args:
            word_timestamps: List of WordTimestamp objects from Whisper.
        """
        self.words = word_timestamps
        self._last_used_index = 0  # Track position for sequential search

        logger.debug(
            "[TimingAligner] Initialized with %d word timestamps, last_used_index=0",
            len(self.words),
        )

    def find_timing_for_text(self, text: str) -> TextMatch:
        """Find start/end times for a given text excerpt.

        Strategy (sequential search):
        1. Extract first and last words from the text
        2. Find their positions in the word timestamp list (searching forward from _last_used_index)
        3. Return the corresponding timestamps
        4. Update _last_used_index so next segment continues from here

        Args:
            text: The text excerpt to find timing for.

        Returns:
            TextMatch with start_time, end_time, and confidence.

        Raises:
            ValueError: If no words can be extracted from the text.
        """
        # Normalize text for matching
        words_in_text = self._extract_words(text)
        if not words_in_text:
            raise ValueError(f"No words found in text: {text}")

        first_word = words_in_text[0].lower().strip('.,!?;:"')
        last_word = words_in_text[-1].lower().strip('.,!?;:"')

        logger.debug(
            "[TimingAligner] Finding timing for text: %r (first_word=%r, last_word=%r, word_count=%d)",
            text[:60],
            first_word,
            last_word,
            len(words_in_text),
        )

        # Find first word occurrence (search from last position)
        start_idx = self._find_word_index(first_word, search_from=self._last_used_index)

        # Find last word occurrence (search after first word or from last position)
        search_from_for_end = start_idx if start_idx is not None else self._last_used_index
        end_idx = self._find_word_index(last_word, search_from=search_from_for_end)

        if start_idx is None:
            # Fallback: estimate from word count
            logger.warning(
                "[TimingAligner] Could not find first word %r, using estimation fallback",
                first_word,
            )
            return self._estimate_from_word_count(text)

        if end_idx is None:
            # Estimate end index based on word count
            end_idx = start_idx + len(words_in_text) - 1
            if end_idx >= len(self.words):
                end_idx = len(self.words) - 1
            logger.warning(
                "[TimingAligner] Could not find last word %r, estimating end_idx=%d",
                last_word,
                end_idx,
            )

        start_time = self.words[start_idx].start
        end_time = self.words[end_idx].end

        # Update last used index for next segment
        self._last_used_index = end_idx + 1

        # Calculate confidence based on how well the text matched
        confidence = 1.0 if (start_idx is not None and end_idx is not None) else 0.5

        logger.debug(
            "[TimingAligner] ✓ Matched: start_idx=%d, end_idx=%d, start_time=%.2fs, end_time=%.2fs, confidence=%.2f",
            start_idx,
            end_idx,
            start_time,
            end_time,
            confidence,
        )

        return TextMatch(start_time=start_time, end_time=end_time, confidence=confidence)

    def _extract_words(self, text: str) -> list[str]:
        """Extract words from text, preserving order.

        Args:
            text: The text to extract words from.

        Returns:
            List of words in order.
        """
        return re.findall(r'\b\w+\b', text)

    def _find_word_index(self, word: str, search_from: int = 0) -> Optional[int]:
        """Find a word in the timestamp list.

        Args:
            word: The word to search for (already normalized/lowercase).
            search_from: The index to start searching from.

        Returns:
            The index of the word, or None if not found.
        """
        word = word.lower()
        for i in range(search_from, len(self.words)):
            # Normalize the word from timestamp for comparison
            timestamp_word = self.words[i].word.lower().strip('.,!?;:"\'')
            if timestamp_word == word:
                logger.debug(
                    "[TimingAligner] Found word %r at index %d (searched from %d)",
                    word,
                    i,
                    search_from,
                )
                return i

        logger.debug(
            "[TimingAligner] Word %r not found (searched from %d to %d)",
            word,
            search_from,
            len(self.words) - 1,
        )
        return None

    def _estimate_from_word_count(self, text: str) -> TextMatch:
        """Fallback estimation when exact match fails.

        Args:
            text: The text to estimate duration for.

        Returns:
            TextMatch with estimated timing.
        """
        word_count = len(self._extract_words(text))
        estimated_duration = word_count * 0.4  # seconds per word

        # Find next available position
        if self._last_used_index < len(self.words):
            start_time = self.words[self._last_used_index].start
        else:
            start_time = 0.0

        end_time = start_time + estimated_duration

        logger.warning(
            "[TimingAligner] Estimated timing for %d words: start=%.2fs, end=%.2fs, duration=%.2fs",
            word_count,
            start_time,
            end_time,
            estimated_duration,
        )

        return TextMatch(start_time=start_time, end_time=end_time, confidence=0.5)

    def reset(self) -> None:
        """Reset the sequential search position to the beginning.

        This is useful when re-using the aligner for a new script.
        """
        self._last_used_index = 0
        logger.debug("[TimingAligner] Reset last_used_index to 0")


__all__ = ["TextToTimestampAligner", "TextMatch"]
